name=TimberWidget
version=0.0.8
author=Ivan
maintainer=Ivan
sentence=Arduino C++ widget sender for Timber Android console widgets with StringN buffers.
paragraph=Provides a simple one-method API via TimberWidgets and a low-level builder for advanced Timber Android widget commands.
category=Communication
url=https://github.com/Sacamoto84/CPP_TimberWidget
architectures=*
depends=StringN
